# https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md

binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
color = "Never"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
edition = "Edition2018"
empty_item_single_line = true
error_on_line_overflow = false
error_on_unformatted = false
fn_args_density = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_strings = true
hard_tabs = false
hide_parse_errors = false
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Visual"
match_arm_blocks = true
match_block_trailing_comma = true
max_width = 140
merge_derives = true
merge_imports = false
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = false
reorder_imports = true
reorder_modules = true
report_todo = "Never"
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = false
tab_spaces = 2
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = false
where_single_line = false
wrap_comments = true
